onboarding = false
[ui]
agent_panel_sort = "spaces"
pane_gaps = false
pane_outer_borders = false
pane_scrollbars = false

[keys]
prefix = "ctrl+a"

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"
