"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](#2f334d)\
$os\
$username\
[](bg:#3b4261 fg:#2f334d)\
$directory\
[](fg:#3b4261 bg:#444a73)\
$git_branch\
$git_status\
[](fg:#444a73 bg:#4a527d)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4a527d bg:#394b70)\
$docker_context\
[](fg:#394b70 bg:#2d3f5f)\
$time\
[ ](fg:#2d3f5f)\
$line_break\
$character
"""

[username]
show_always = true
style_user = "bg:#2f334d fg:#c8d3f5"
style_root = "bg:#2f334d fg:#ff757f"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#2f334d fg:#82aaff"
disabled = true

[directory]
style = "bg:#3b4261 fg:#82aaff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#4a527d fg:#86e1fc"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#4a527d fg:#86e1fc"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#394b70 fg:#7dcfff"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#4a527d fg:#c099ff"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#4a527d fg:#86e1fc"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#444a73 fg:#c099ff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#444a73 fg:#ff757f"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#4a527d fg:#86e1fc"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4a527d fg:#c3e88d"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#4a527d fg:#c099ff"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#4a527d fg:#ff966c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#4a527d fg:#c099ff"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4a527d fg:#c3e88d"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#4a527d fg:#ffc777"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4a527d fg:#ff966c"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#4a527d fg:#ff757f"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#2d3f5f fg:#ffc777"
format = '[ ♥ $time ]($style)'
