# 将 prefix 改为 ctrl + a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# get Catppuccin Tmux theme
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"


set -g status-left-length 24
set -g status-right-length 32
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_date_time}"

set -g default-terminal 'tmux-256color'

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g allow-rename off
set -g automatic-rename off

# true color
set -ga terminal-overrides ",*:Tc"

set -sg escape-time 0
set -g focus-events on

# increase scrolling history
set -g history-limit 100000

# mouse control
set -g mouse on

# connect with system clipboard
set -g set-clipboard on
setw -g mode-keys vi
setw -g xterm-keys on

# 分屏 / 新窗口
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Pane/Window 导航
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind Tab last-window
bind n next-window
bind p previous-window
bind , command-prompt -I "#W" "rename-window '%%'"

# 会话/查找 
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind s choose-tree -Zs
bind f choose-tree -Zw
bind w choose-window -Z

# 复制模式
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-yank
set -g @yank_action 'copy-pipe'

# tmux-resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-strategy-vim 'session'

set -g @continuum-restore 'on'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
