# 基础 
shell /bin/zsh
confirm_os_window_close 0
enabled_layouts tall,stack,splits
scrollback_lines 10000


# 字体 
font_family      family="Lilex Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0

#Lilex 字体略微放松行高，观感更舒展
adjust_line_height 110%
adjust_column_width 100%


# macOS 窗口外观 

#隐藏顶部标题栏，但保留 macOS 原生圆角
hide_window_decorations titlebar-only

#隐藏 macOS 窗口标题文字
macos_show_window_title_in none

#标题栏颜色跟随系统
macos_titlebar_color system

#防止隐藏标题栏后，左上/右上圆角区域裁切文字
window_margin_width 6
single_window_margin_width 6
window_padding_width 10
single_window_padding_width 10
placement_strategy center

#轻微透明 + 轻微模糊
#opacity 不要太低，blur 不要太高，兼顾观感和性能
background_opacity 1
dynamic_background_opacity no

#窗口边框
#单窗口不画边框，split 时才用边框区分
window_border_width 1pt
draw_minimal_borders yes
draw_window_borders_for_single_window no

#非活跃 split 稍微淡一点
inactive_text_alpha 0.85


# Tab 栏 

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_separator "  "
tab_bar_align left
tab_bar_min_tabs 2
tab_bar_show_new_tab_button no
tab_title_max_length 24
tab_title_template "{index}: {((tab.active_wd.rstrip('/').rsplit('/', 1)[-1] or '/') if tab.active_exe.rsplit('/', 1)[-1].lstrip('-') in ('zsh', 'bash', 'fish') else tab.active_exe.rsplit('/', 1)[-1].lstrip('-'))}"

# 光标 
cursor_shape block
cursor_shape_unfocused hollow

#光标闪烁：0 是关闭闪烁，正数是闪烁间隔，单位秒
cursor_blink_interval 0.43 ease-in-out

#0 表示永不停止闪烁
cursor_stop_blinking_after 0


# 快捷键：Tab 管理 
map cmd+t new_tab
map cmd+w close_tab
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9


# 快捷键：窗口 / Split 管理 
map cmd+enter new_window
map cmd+d launch --location=vsplit
map cmd+shift+d launch --location=hsplit
map cmd+shift+w close_window
map cmd+alt+h neighboring_window left
map cmd+alt+j neighboring_window down
map cmd+alt+k neighboring_window up
map cmd+alt+l neighboring_window right


# 快捷键：布局 
map cmd+shift+l next_layout
